config/routes.rb
Makehub::Application.routes.draw do
  get "welcome/index"
  get "me/projects" => 'me#index'

  resources :media_objects

  resources :projects do
    member do
      post :fork
    end
    resources :steps
    resources :materials
  end

  resources :users, except: [:new, :create] do
    resources :projects
  end
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete "sessions/destroy" => 'sessions#destroy', as: :signout

  root 'welcome#index'

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :project, inverse_of: :steps, touch: true
  has_many :media_objects, inverse_of: :step

  accepts_nested_attributes_for :media_objects

  before_validation(on: :create) do
    self.position = self.project.number_of_steps
  end

  # with Authority we control permissions. (i.e. `creatable_by?(user)`)
  # Check out /app/authorizers or read https://github.com/nathanl/authority
  include Authority::Abilities

  validates_presence_of :project_id, :name, :content, :position
  validates :position, numericality: { only_integer: true },
                       uniqueness: { scope: :project_id }

  def fork(project_id)
    new_step = self.dup
    new_step.project_id = project_id
    new_step.save

    self.media_objects.to_a.map { |mo| mo.fork(new_step.id) }
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_project
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @steps = @project.steps.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    render 'projects/show'
  end

  # GET /steps/new
  def new
    @step = @project.steps.new
    authorize_action_for(@step)
    render 'projects/edit'
  end

  # GET /steps/1/edit
  def edit
    render 'projects/edit'
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @project.steps.new(step_params)
    authorize_action_for(@step)
    @project.steps << @step

    respond_to do |format|
      if @step.save
        @project.save
        format.html { redirect_to edit_project_step_path(@project, @step), notice: 'Step was successfully created.' }
        format.json { render action: 'show', status: :created, location: @step }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to edit_project_step_path(@project, @step), notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to project_steps_url(@project) }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = @project.steps.find(params[:id])
      authorize_action_for(@step)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:name, :content, media_objects_attributes: [:name, :image, :id])
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_for([@project, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/steps/_media_object_fields.html.erb
<div class="media_object row-fluid">
  <div class="span8">
    <%= f.label :image, 'Pictures -- Select a file to upload' %>
    <%= f.file_field :image%>
  </div>
  <div class="span4">
    <%= image_tag f.object.image.url(:thumb) %>
  </div>
</div>

app/views/steps/edit.html.erb
<div class="container">
  <h1>Editing step</h1>

  <%= render 'step_form' %>

  <%= link_to 'Show', project_step_path(@project, @step) %> |
  <%= link_to 'Back', project_steps_path(@project) %>
</div>

app/views/steps/index.html.erb
<div class="container">
  <h1>Listing steps</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Content</th>
        <th>Project</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @steps.each do |step| %>
        <tr>
          <td><%= step.name %></td>
          <td><%= step.content %></td>
          <td><%= step.project_id %></td>
          <td><%= link_to 'Show', project_step_path(@project, step) if can_read?(step) %></td>
          <td><%= link_to 'Edit', edit_project_step_path(@project, step) if can_update?(step) %></td>
          <td><%= link_to 'Destroy', project_step_path(@project, step), method: :delete, data: { confirm: 'Are you sure?' } if can_delete?(step) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Step', new_project_step_path(@project) if can_create?(@project.steps.new) %>
</div>

app/views/steps/new.html.erb
<div class="container">
  <h1>New step</h1>

  <%= render 'step_form' %>

  <%= link_to 'Back', project_steps_path(@project) %>
</div>

app/views/steps/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @step.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @step.content %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= @step.project_id %>
  </p>

  <%= link_to 'Edit', edit_project_step_path(@project, @step) if can_update?(@step) %> |
  <%= link_to 'Back', project_steps_path(@project) %>
</div>