config/routes.rb
Makehub::Application.routes.draw do
  get "welcome/index"
  get "me/projects" => 'me#index'

  resources :media_objects

  resources :projects do
    member do
      post :fork
    end
    resources :steps
    resources :materials
  end

  resources :users, except: [:new, :create] do
    resources :projects
  end
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete "sessions/destroy" => 'sessions#destroy', as: :signout

  root 'welcome#index'

end

app/models/material.rb
class Material < ActiveRecord::Base
  has_and_belongs_to_many :projects

  validates_presence_of :name

  # for the time being, any user can create, edit and destroy any material.
  # eventually we will have either admins or users that own materials
  # we need to find a way that makes sense, so projects can share materials.
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_project
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = @project.materials.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = @project.materials.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = @project.materials.new(material_params)
    @project.materials << @material #this is so stupid

    respond_to do |format|
      if @material.save
        @project.save
        format.html { redirect_to project_material_path(@project, @material), notice: 'Material was successfully created.' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to project_material_path(@project, @material), notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to project_materials_url(@project) }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = @project.materials.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :url, :photo_url)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for([@project, @material]) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<div class="container">
  <h1>Editing material</h1>

  <%= render 'form' %>

  <%= link_to 'Show', project_material_path(@project, @material) %> |
  <%= link_to 'Back', project_materials_path(@project) %>
</div>

app/views/materials/index.html.erb
<div class="container">
  <h1>Listing materials</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Url</th>
        <th>Photo url</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @materials.each do |material| %>
        <tr>
          <td><%= material.name %></td>
          <td><%= material.url %></td>
          <td><%= material.photo_url %></td>
          <td><%= link_to 'Show', project_material_path(@project, material) %></td>
          <td><%= link_to 'Edit', edit_project_material_path(@project, material) %></td>
          <td><%= link_to 'Destroy', project_materials_path(@project, material), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Material', new_project_material_path(@project) %>
</div>

app/views/materials/new.html.erb
<div class="container">
  <h1>New material</h1>

  <%= render 'form' %>

  <%= link_to 'Back', project_materials_path(@project) %>
</div>

app/views/materials/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @material.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @material.url %>
  </p>

  <p>
    <strong>Photo url:</strong>
    <%= @material.photo_url %>
  </p>

  <%= link_to 'Edit', edit_project_material_path(@project, @material) %> |
  <%= link_to 'Back', project_materials_path(@project) %>
</div>