config/routes.rb
Makehub::Application.routes.draw do
  get "welcome/index"
  get "me/projects" => 'me#index'

  resources :media_objects

  resources :projects do
    member do
      post :fork
    end
    resources :steps
    resources :materials
  end

  resources :users, except: [:new, :create] do
    resources :projects
  end
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete "sessions/destroy" => 'sessions#destroy', as: :signout

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  delegate :can_read?, :can_create?, :can_update?, :can_delete?, :can_fork?, to: :current_user
  helper_method :can_read?, :can_create?, :can_update?, :can_delete?, :can_fork?

  private
    def current_user
      # comment this line if you want to be able to log-in in development.
      return @current_user ||= User.first if Rails.env.development?

      if session[:user_id] then
        @current_user ||= User.find(session[:user_id])
      else
        # we create a new user for the Authority Gem
        @current_user = User.new
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    # check for ID because we always have a current user
    current_user && current_user.id.present?
  end

  def nav_link(link_text, link_path, html_opts = {})
    active = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => "#{html_opts[:class]} #{active}") do
      link_to link_text, link_path
    end
  end

  def markdownify(content)
    @@markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @@markdown.render(content)
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub('\n', ''),
                                                    :'no-turbolink' => true })
  end
end

app/views/application/_add_step_instructions.html.erb
<p>A step has a title and some instructions.</p>
<p>You can use some simple markup</p>

<p>You can also add pictures</p>

app/views/application/_edit_project_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'project_form_errors' %>
  <div class="actions">
    <%= f.submit 'save', :class => 'btn btn-primary' %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'xlarge' %>
  <div class="field">
    <div class="row">
      <div class="span3">
        <%= f.label :skills %>
        <%= select_for_project f, :skills, {}, { multiple: 'multiple' } %>
      </div>
      <div class="span3">
        <%= f.label :duration%>
        <%= select_for_project f, :duration %>
      </div>
      <div class="span3">
        <%= f.label :price%>
        <%= select_for_project f, :price %>
      </div>
      <div class="span3">
        <%= f.label :license%>
        <%= select_for_project f, :license %>
      </div>
    </div>
  </div>
  <div class="actions see_project">
    <%= link_to 'See how other users see this project', project_path(@project) %>
  </div>
<% end %>

app/views/application/_project_form_errors.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_project_steps.html.erb
<% editable = editable || false %>
<section class="project-steps">
  <% @step = @step || @project.steps.first unless editable %>
  <div class="row">
    <ol class="span3 steps_nav">
      <% if editable %>
        <%= link_to edit_project_path(@project), class: "#{'active' unless @step}" do %>
          <li>How to</li>
        <% end %>
      <% end %>
      <% @project.steps.order(:position).each_with_index do |step, index| %>
        <% link_class = "active" if(@step and @step.id == step.id) %>
        <%= step_nav_link_for(@project, step, editable, link_class) %>
      <% end %>
      <% if editable %>
        <%= link_to new_project_step_path(@project) do %>
          <li class="add_step">Add step<i class="icon-plus icon-white"></i></li>
        <% end %>
      <% end %>
    </ol>
    <div class="step_content span9">
      <div class="content">
        <% if editable %>
          <% if @step %>
            <%= render 'step_form' %>
          <% else %>
            <%= render 'add_step_instructions' %>
          <% end %>
        <% else %>
          <h3><%= markdownify(@step.name).html_safe %></h3>
          <% @step.media_objects.each_with_index do |media_object, i| %>
            <% if i == 0 %>
              <%= image_tag media_object.image.url(:medium) %>
            <% else %>
              <%= image_tag media_object.image.url(:thumb) %>
            <% end %>
          <% end%>
          <p><%= markdownify(@step.content).html_safe %></p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/application/_step_form.html.erb
<%= form_for([@project, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'save step', :class => 'btn btn-primary' %>
  </div>
  <div class="field">
    <% step_label = "-- Step #{(f.object.position + 1)}" unless f.object.new_record? %>
    <%= f.label :name, "Title #{step_label}" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content, "Instructions #{step_label}" %>
    <%= f.text_area :content, rows: 5 %>
  </div>
  <% if @step.media_objects.count > 0 %>
    <%= f.fields_for :media_objects do |mo_f| %>
      <%= render 'media_object_fields', f: mo_f %>
    <% end %>
    <%= link_to_add_fields "Add another picture", f, :media_objects %>
  <% else %>
    <%= link_to_add_fields "Add picture", f, :media_objects %>
  <% end %>
<% end %>