config/routes.rb
Makehub::Application.routes.draw do
  get "welcome/index"
  get "me/projects" => 'me#index'

  resources :media_objects

  resources :projects do
    member do
      post :fork
    end
    resources :steps
    resources :materials
  end

  resources :users, except: [:new, :create] do
    resources :projects
  end
  get '/auth/google_oauth2/callback' => 'sessions#create'
  delete "sessions/destroy" => 'sessions#destroy', as: :signout

  root 'welcome#index'

end

app/views/layouts/_footer.html.erb
<footer class="hck-mastfoot">
  <p>This is the footer content, Makehub &copy; and stuffs...</p>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top makehub-nav">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Makehub", root_path, :class => 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= nav_link 'Explore', projects_path %>
        </ul>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <%= nav_link 'Add New Project', new_project_path, class: "hck-new-project-link" %>
            <%= nav_link 'My Labs', user_projects_path(current_user) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user icon-white"></i>
                <%= current_user.name %>
                <i class="caret"></i>
              </a>
              <ul class="dropdown-menu">
                <%= nav_link "My Account", user_path(current_user) %>
                <li class="divider"></li>
                <li><%= link_to "Log Out", signout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class='account_sign_in'><%= link_to "Account", "/auth/google_oauth2" %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Makehub</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <style>
  body {
    padding-top: 40px;
  }
  </style>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/navigation' %>

  <div class="main-container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>